function scripts:clearmemory
setblock ~26 ~7 ~ black_concrete replace
setblock ~26 ~6 ~ black_concrete replace
setblock ~25 ~7 ~ lime_concrete replace
setblock ~25 ~6 ~ light_blue_concrete replace
setblock ~25 ~3 ~ yellow_concrete replace
setblock ~24 ~7 ~ lime_concrete replace
setblock ~24 ~4 ~ red_concrete replace
setblock ~23 ~7 ~ green_concrete replace
setblock ~23 ~6 ~ orange_concrete replace
setblock ~23 ~4 ~ red_concrete replace
setblock ~22 ~7 ~ magenta_concrete replace
setblock ~22 ~6 ~ light_blue_concrete replace
setblock ~22 ~3 ~ lime_concrete replace
setblock ~21 ~7 ~ light_gray_concrete replace
setblock ~21 ~6 ~ orange_concrete replace
setblock ~21 ~4 ~ red_concrete replace
setblock ~19 ~7 ~ light_blue_concrete replace
setblock ~19 ~4 ~ red_concrete replace
setblock ~18 ~4 ~ orange_concrete replace
setblock ~17 ~7 ~ cyan_concrete replace
setblock ~16 ~7 ~ red_concrete replace
setblock ~15 ~7 ~ magenta_concrete replace
setblock ~14 ~7 ~ lime_concrete replace
setblock ~14 ~6 ~ light_blue_concrete replace
setblock ~14 ~3 ~ yellow_concrete replace
setblock ~13 ~7 ~ orange_concrete replace
setblock ~13 ~6 ~ magenta_concrete replace
setblock ~13 ~4 ~ orange_concrete replace
setblock ~12 ~7 ~ magenta_concrete replace
setblock ~12 ~6 ~ light_blue_concrete replace
setblock ~12 ~3 ~ yellow_concrete replace
setblock ~11 ~7 ~ lime_concrete replace
setblock ~11 ~4 ~ orange_concrete replace
setblock ~10 ~7 ~ green_concrete replace
setblock ~10 ~6 ~ orange_concrete replace
setblock ~10 ~4 ~ orange_concrete replace
setblock ~9 ~7 ~ magenta_concrete replace
setblock ~9 ~6 ~ light_blue_concrete replace
setblock ~9 ~3 ~ lime_concrete replace
setblock ~8 ~7 ~ light_gray_concrete replace
setblock ~8 ~6 ~ orange_concrete replace
setblock ~8 ~4 ~ orange_concrete replace
setblock ~6 ~7 ~ light_blue_concrete replace
setblock ~6 ~4 ~ orange_concrete replace
setblock ~5 ~4 ~ orange_concrete replace
setblock ~4 ~7 ~ cyan_concrete replace
setblock ~3 ~7 ~ orange_concrete replace
setblock ~2 ~7 ~ magenta_concrete replace
setblock ~1 ~7 ~ magenta_concrete replace
setblock ~1 ~6 ~ light_blue_concrete replace
setblock ~1 ~3 ~ yellow_concrete replace
setblock ~ ~6 ~ light_blue_concrete replace
setblock ~ ~4 ~ black_concrete replace
setblock ~ ~3 ~ gray_concrete replace
